# NB: short workspace name is required to workaround PATH length limitation, see
# https://github.com/bazelbuild/bazel/issues/18683#issuecomment-1843857373
workspace(name = "p")

# The following local_path_override is only needed to run this example as part of our CI.
local_repository(
    name = "rules_python",
    path = "../..",
)

# When not using this example in the rules_python git repo you would load the python
# rules using http_archive(), as documented in the release notes.

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

# We install the rules_python dependencies using the function below.
py_repositories()

# Needed for rules_cc 0.2.10
load("@bazel_features//:deps.bzl", "bazel_features_deps")
bazel_features_deps()

load("@rules_cc//cc:extensions.bzl", "compatibility_proxy_repo")
compatibility_proxy_repo()

python_register_toolchains(
    name = "python39",
    python_version = "3.9",
)

# Then we need to setup dependencies in order to use py_proto_library
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

# Needed to load @compatibility_proxy for rules_java
load("@rules_java//java:rules_java_deps.bzl", "rules_java_dependencies")
rules_java_dependencies()
